# Generated by Django 5.1.7 on 2025-03-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='image',
        ),
        migrations.AddField(
            model_name='radiostation',
            name='current_listeners',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='monthly_plays',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
