# Generated by Django 5.1.7 on 2025-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_remove_station_image_radiostation_current_listeners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
