# Generated by Django 5.1.7 on 2025-03-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_radiostation_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiostation',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='owner',
        ),
    ]
